### ISSUE TITLE
[Clarification] Missing vs empty values in `said.csv`

### ISSUE THREAD

**Issue by syvwlch** [syvwlch/Data-Ignota#17]
** What needs to be clarified **

Establish distinction between missing data and correctly empty values in `said.csv` file.

**Comment by syvwlch** [comment]
- [ ] Research proper usage
			- [ ] Update xquery
			- [ ] Update data cleanup
			- [ ] Update column descriptions
			- [ ] Publish updated file

**Comment by cdrigby** [comment]
I may be missing something here, but for the first point under define usage, should that not be NULL? That would do the equivalent of throwing an exception, flagging a line that _is_ invalid.

**Comment by syvwlch** [comment]
In __R__ , as far as I currently understand it, if I put _NULL_ in a cell of a row of data, some data objects will just flat out throw an error, and for the ones that don't, the cell will invalidate or even delete the entire row, which is not what I want.

Perhaps 'required' is not the right word. 

I aspire to having a valid `speaker` and a valid `addressee` parameter set for every single `<said>` element in the digital edition, but I don't want the code to barf & stop when it hits one. Instead I will have a dashboard to shows the progress of the editing process by counting how many _NA_ remain for these 'required' columns.

**Comment by cdrigby** [comment]
OK, that's how it works. Indeed, having an error stop everything is not good and aggravating as can be.
