### ISSUE TITLE
[Feature] Persistent Mapping of Characters to Emojis

### ISSUE THREAD

**Issue by syvwlch** [syvwlch/Data-Ignota#26]
**Is your feature request related to a problem? Please describe.**

It's going to become necessary to concisely label the main characters on various plots and graphs very soon.

**Describe the solution you'd like**

Unlike numbers or colors with a key off to the side, Emojis offer the possibility of being remembered fairly easily, making the key just a reminder rather than something that must be constantly checked to interpret a visualization.

Started a discussion [here](https://github.com/syvwlch/Data-Ignota/discussions/25) to collect ideas for individual emojis.

**Comment by cdrigby** [comment]
I like it. Perhaps if display is to a web browser or some such, displaying the character name on mouse-over may also be helpful.

**Comment by syvwlch** [comment]
https://github.com/ikatyang/emoji-cheat-sheet

**Comment by syvwlch** [comment]
Please propose emojis here: https://github.com/syvwlch/Data-Ignota/discussions/25

This issue is more for implementation tracking?

**Comment by cdrigby** [comment]
> https://github.com/ikatyang/emoji-cheat-sheet

Nice. That's useful for me in general.

Seeing as how you've done an excellent job of engaging our readers' group by tossing this item to them, though, I'm going to leave it to them. They know the topic better than I.

**Comment by syvwlch** [comment]
Speaking of implementation details:

- Assign the emoji directly to the character's `<person>` node in the digital edition's `standoff` section, just like any other form of metadata I'm adding alongside the text of the novels
- Treat them like any other `<persName>` sub-node, but with a type of `emoji`.
- Keep the `primary` name, but add a `short` name type as well, to build keys or to use as a label when the emoji's brevity is not needed
- Create an Xquery script that generates an input file with at least:
  - the unique ID
  - the `short` name
  - the `emoji` name
- Ingest in R and generate the CSV file to share on the site
- Demo using a left join to add the emojis to a plot.

**Comment by syvwlch** [comment]
The source of truth is always the digital edition, Xquery and R manipulate the data but the data always comes from the TEI-schema XML of the books themselves.

**Comment by syvwlch** [comment]
Oooookay. 

Turns out displaying an Emoji on a ggplot graph is not trivial. 

🤪

More research and experiments needed.

**Comment by syvwlch** [comment]
May have found the solution:

https://github.com/r-lib/ragg
