### ISSUE TITLE
[Clarification] Explain the `group_by()` & `summarize()` pattern

### ISSUE THREAD

**Issue by syvwlch** [syvwlch/Data-Ignota#41]
** What needs to be clarified **

It's not clear how and why the lines of dialog need to be deduped depending on what we're trying to analyze or count.

** Page(s) which need to be clarified (Optional) **

Verbosity viz post: https://syvwlch.github.io/Data-Ignota/viz/2022-10-09-exploring-verbosity/

**Comment by cdrigby** [comment]
The violin plots really do seem a good choice for visualization of the results.

A couple questions/observations

The deduplication table immediately under the title "Overall Verbosity" showing who Mycroft addresses in line two made me wonder about de-referencing personal pronouns. I believe that's in the markup in the private repository, but I wonder how you did that?

Again not having the text for reference and comparing violin-plots "Verbosity by Language" and Mycroft's "Verbosity by Addressee," I wonder: are we seeing an aspect of Japanese-Mitsubishi as translated into English, or could we be teasing out the hierarchy of dominance we discussed a while back? My recollection is that Mycroft is being subservient w/ Ando & Danae.

**Comment by syvwlch** [comment]
Yeah, the violin lots are a huge improvement over the box plots!

1. In the Digital Edition, I'm marking up names, but not pronoun. So the `person` column in the data indicates who is mentioned by name, not who is mentioned by a pronoun. I quailed at the thought of going that far, if I'm honest.
2. I do believe it's a reflection of the power dynamic, as you suggest. In particular under threat from Ando and under sexy-wiles from Danaë our Mycroft does start to blabber rather a lot. So the distribution is bi-modal: short answers for normal convo and loquacious when under applied persistent pressure to reveal more?

**Comment by cdrigby** [comment]
>     1. In the Digital Edition, I'm marking up names, but not pronoun. So the `person` column in the data indicates who is mentioned by name, not who is referenced by a pronoun. I quailed at the thought of going that far, if I'm honest.

Understandable. 

>     2. I do believe it's a reflection of the power dynamic, as you suggest. In particular under threat from Ando and under sexy-wiles from Danaë our Mycroft does start to blabber rather a lot. So the distribution is bi-modal: short answers for normal convo and loquacious when under applied persistent pressure to reveal more?

Yes, that makes intuit sense to me.

**Comment by syvwlch** [comment]
I am planning to add scene milestones at a later date. These would indicate who is present from that point until the next scene change.

So no pronouns but we would know if persons mentioned are there or not.
