### ISSUE TITLE
[Feature] Try Ridgeline Plots?

### ISSUE THREAD

**Issue by syvwlch** [syvwlch/Data-Ignota#45]
**Is your feature request related to a problem? Please describe.**

Violin plots are nice but they take a lot of space and are not easy to compare...

**Describe the solution you'd like**

Try ridgeline plots instead?

**Additional context**

https://wilkelab.org/ggridges/

**Comment by cdrigby** [comment]
I'd say give it a shot. It will be interesting to compare that with the violin plots.

Heh. Also, you're the one doing all the work so yeah, have at it!

**Comment by syvwlch** [comment]
Tried it, and it works just fine, but in the case of the existing posts the violin plot works better to get the point across.
A new tool in the toolbox, but no use right this moment.
