### ISSUE TITLE
[Analysis] Data Files for Book, Chapter, Character

### ISSUE THREAD

**Issue by syvwlch** [syvwlch/Data-Ignota#51]
** Describe the analysis **

Add data files for some of the low-hanging fruit already present as metadata in the Digital Edition's XML file. 

** Output **

Book can have title, author, page count, chapter IDs?

Chapter can have title and subtitle, page count, book ID?

Character can have various names, inc. optional emoji?

**Comment by syvwlch** [comment]
These will get enriched as we go, e.g. org memberships for characters, or scene IDs for chapters?

**Comment by cdrigby** [comment]
Do you that this, in conjunction with current the conversation analysis, could provide a result indicating what a particular segment (book, chapter, etc.) tells us about which characters are most important, dominant, etc. in that segment?

Perhaps it could help elucidate patterns of change in a particular character's significance, status, etc. over the course of the containing segment. I. e., the changes for a character over an entire book by analyzing the shift in the status of a given character chapter by chapter, given that a book segment contains chapter segments.
